# fly.toml app configuration file generated for filmreel on 2026-02-21T16:36:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'filmreel'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'node_modules/.bin/prisma migrate deploy'

[env]
  AUTO_MIGRATE = '0'
  BULL_BOARD_PORT = '3001'
  NODE_ENV = 'production'
  REDIS_DB_INDEX = '1'

[processes]
  bot = 'node dist/bot/index.js'
  bullboard = 'node dist/bullboard/index.js'
  scheduler = 'node dist/scheduler/index.js'
  worker = 'node dist/worker/index.js'

[[services]]
  protocol = 'tcp'
  internal_port = 3001
  processes = ['bullboard']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '20s'
    method = 'get'
    path = '/healthz'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
